package HospitalManagmentSystem;
public enum Department {
    UROLOGY,
    RADIOLOGY,
    CARDIOLOGY,
    DERMATOLOGY,
    GASTROENTEROLOGY,
    NEUROLOGY,
    OBSTETRICS_GYNECOLOGY,
    OPHTHALMOLOGY,
    ORTHOPEDICS,
    PEDIATRICS,
    PSYCHIATRY
}